apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-with-postgres
  labels:
    app: auth-with-postgres
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-with-postgres
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
  template:
    metadata:
      labels:
        app: auth-with-postgres
    spec:
      containers:
        - name: auth-with-postgres
          image: yashanthilakasiri/auth-with-postgres
          imagePullPolicy: Always  
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: auth-configmap
            - secretRef:
                name: auth-secret
