apiVersion: v1
kind: Service
metadata:
  name: auth-with-posgres
spec:
  selector:
    app: auth-with-posgres
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP